[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "app/static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/app/static/:splat"
  status = 200